server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    com.phonepe.epoch: INFO

  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST

zookeeper:
  connectionString: ${ZK_CONNECTION_STRING}

drove:
  endpoints:
  - ${DROVE_ENDPOINT}
  username: ${DROVE_USERNAME}
  password: ${DROVE_PASSWORD}

userAuth:
  enabled: true
  users:
  - username: admin
    password: ${EPOCH_ADMIN_PASSWORD}
    role: READ_WRITE

  - username: guest
    password: ${EPOCH_GUEST_PASSWORD}
    role: READ_ONLY

options:
  cleanupJobInterval: 30m
  numRunsPerJob: 20
