server:
  applicationConnectors:
    - type: http
      port: 6200
  adminConnectors:
    - type: http
      port: 6201
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST
  gzip:
    syncFlush: true

logging:
  level: INFO
  loggers:
#    com.phonepe.drove: DEBUG
    com.phonepe.epoch: DEBUG

  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST

zookeeper:
  connectionString: localhost:2181

drove:
  endpoints:
  - http://localhost:10000

userAuth:
  enabled: true
  users:
  - username: admin
    password: admin
    role: READ_WRITE

  - username: guest
    password: guest
    role: READ_ONLY

notify:
  type: MAIL
  smtpServer: sandbox.smtp.mailtrap.io
  port: 2525
  username: ${EMAIL_USER}
  password: ${EMAIL_PASSWORD}
  defaultEmails:
    - ${DEV_EMAIL}

options:
  cleanupJobInterval: 30m
  numRunsPerJob: 20
